// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AcceptRuleRequest struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptRuleRequest) Reset()         { *m = AcceptRuleRequest{} }
func (m *AcceptRuleRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptRuleRequest) ProtoMessage()    {}
func (*AcceptRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *AcceptRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptRuleRequest.Unmarshal(m, b)
}
func (m *AcceptRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptRuleRequest.Marshal(b, m, deterministic)
}
func (m *AcceptRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRuleRequest.Merge(m, src)
}
func (m *AcceptRuleRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptRuleRequest.Size(m)
}
func (m *AcceptRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRuleRequest proto.InternalMessageInfo

func (m *AcceptRuleRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type DropRuleRequest struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Pattern              string   `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropRuleRequest) Reset()         { *m = DropRuleRequest{} }
func (m *DropRuleRequest) String() string { return proto.CompactTextString(m) }
func (*DropRuleRequest) ProtoMessage()    {}
func (*DropRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *DropRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropRuleRequest.Unmarshal(m, b)
}
func (m *DropRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropRuleRequest.Marshal(b, m, deterministic)
}
func (m *DropRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropRuleRequest.Merge(m, src)
}
func (m *DropRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DropRuleRequest.Size(m)
}
func (m *DropRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropRuleRequest proto.InternalMessageInfo

func (m *DropRuleRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DropRuleRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type Key struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest                 string   `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Key) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "internal.Empty")
	proto.RegisterType((*AcceptRuleRequest)(nil), "internal.AcceptRuleRequest")
	proto.RegisterType((*DropRuleRequest)(nil), "internal.DropRuleRequest")
	proto.RegisterType((*Key)(nil), "internal.Key")
}

func init() {
	proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf)
}

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b,
	0xcc, 0x51, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0x32, 0xe1, 0x12, 0x74, 0x4c,
	0x4e, 0x4e, 0x2d, 0x28, 0x09, 0x2a, 0xcd, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x92, 0xe7, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd5, 0x83,
	0xe9, 0xd2, 0xf3, 0x4e, 0xad, 0x0c, 0x02, 0xc9, 0x28, 0xf9, 0x70, 0xf1, 0xbb, 0x14, 0xe5, 0x17,
	0x90, 0xa2, 0x47, 0x48, 0x82, 0x8b, 0xbd, 0x20, 0xb1, 0x04, 0x24, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8,
	0xc1, 0x19, 0x04, 0xe3, 0x2a, 0x69, 0x73, 0x31, 0x7b, 0xa7, 0x56, 0x0a, 0x09, 0x70, 0x31, 0x17,
	0x17, 0x25, 0x83, 0x4d, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0x52, 0x52, 0x8b, 0x4b,
	0xa0, 0xea, 0xc1, 0x6c, 0xa3, 0x46, 0x46, 0x2e, 0xd6, 0x00, 0x90, 0x9f, 0x84, 0x6c, 0xb9, 0x78,
	0x83, 0x53, 0x4b, 0x10, 0xae, 0x17, 0x92, 0x46, 0xd8, 0x8a, 0xe1, 0x27, 0x29, 0x7e, 0x84, 0x24,
	0xd8, 0xe7, 0x42, 0x96, 0x5c, 0xdc, 0xc1, 0xa9, 0x25, 0x30, 0x6f, 0x08, 0x49, 0x22, 0xe4, 0xd1,
	0xbc, 0x86, 0xa1, 0x35, 0x89, 0x0d, 0x1c, 0x9c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11,
	0x05, 0x0e, 0x63, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	SetAcceptRule(ctx context.Context, in *AcceptRuleRequest, opts ...grpc.CallOption) (*Empty, error)
	SetDropRule(ctx context.Context, in *DropRuleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) SetAcceptRule(ctx context.Context, in *AcceptRuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/internal.Proxy/SetAcceptRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) SetDropRule(ctx context.Context, in *DropRuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/internal.Proxy/SetDropRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	SetAcceptRule(context.Context, *AcceptRuleRequest) (*Empty, error)
	SetDropRule(context.Context, *DropRuleRequest) (*Empty, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) SetAcceptRule(ctx context.Context, req *AcceptRuleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAcceptRule not implemented")
}
func (*UnimplementedProxyServer) SetDropRule(ctx context.Context, req *DropRuleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDropRule not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_SetAcceptRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).SetAcceptRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Proxy/SetAcceptRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).SetAcceptRule(ctx, req.(*AcceptRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_SetDropRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).SetDropRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Proxy/SetDropRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).SetDropRule(ctx, req.(*DropRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAcceptRule",
			Handler:    _Proxy_SetAcceptRule_Handler,
		},
		{
			MethodName: "SetDropRule",
			Handler:    _Proxy_SetDropRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
